name: "porfolio"
services:
  front:
    depends_on:
      - back
    env_file:
      - ./envfile.env
    build:
      context: ./front/portfolio
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  back:
    depends_on:
      - postgres
    build:
      context: ./back/PortfolioBackend
      dockerfile: PortfolioBackend/Dockerfile
    env_file:
      - ./envfile.env
    ports:
      - 55001:8080
      - 55002:8081
  postgres:
    image: postgres:latest
    env_file:
      - ./envfile.env       
    ports:
      - 6543:5432                          
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: