name: "porfolio"
services:
  front:
    build:
      context: ./front/portfolio
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  back:
    build:
      context: ./back/PortfolioBackend
      dockerfile: PortfolioBackend/Dockerfile
    env_file:
      - ./.env
    ports:
      - 55001:8080
      - 55002:8081