name: "porfolio"
services:
  front-dev:
    build:
      context: ./front/portfolio
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front/portfolio:/app
  back:
    build:
      context: ./back/PortfolioBackend
      dockerfile: PortfolioBackend/Dockerfile
    env_file:
      - ./.env
    ports:
      - 55001:8080
      - 55002:8081
