// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioBackend.Context;

#nullable disable

namespace PortfolioBackend.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20241002153122_update column names")]
    partial class updatecolumnnames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioBackend.Models.ProfessionalExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("professional_experiences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Created a web application to streamline the student enrollment process.",
                            EndDate = new DateOnly(2022, 7, 31),
                            StartDate = new DateOnly(2021, 2, 1),
                            Title = "FullStack Developer at MonkeyDDevelopment"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Implemented Nomina360, a web app for human resources management.",
                            EndDate = new DateOnly(2023, 11, 30),
                            StartDate = new DateOnly(2022, 10, 1),
                            Title = "FullStack Developer at Soluciones y Proyectos SA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Developed a client's page using the new version of Shopify Theme Dawn.",
                            EndDate = new DateOnly(2024, 2, 29),
                            StartDate = new DateOnly(2023, 11, 1),
                            Title = "Frontend Developer at CacaoWebStudio"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Created an application to manage the capacitation of operators in Yucatán, México.",
                            EndDate = new DateOnly(2024, 12, 31),
                            StartDate = new DateOnly(2024, 5, 1),
                            Title = "Software Engineer at Dacodes"
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Models.Responsabilitie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_id");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("responsabilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Defining the current enrollment process and its weaknesses.",
                            ExperienceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Design the pages and use cases, with focus on easy use for its users.",
                            ExperienceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Make reviews with the administrative staff and the students of the institute.",
                            ExperienceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Define the correct structure of subjects, students, careers, admin users for the database.",
                            ExperienceId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Be responsible for the frontend, backend, database and release of the application.",
                            ExperienceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Implement readable and clean code, following the best practices.",
                            ExperienceId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Analyze the requirements to implement them correctly.",
                            ExperienceId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Realize unit testing of the functions created.",
                            ExperienceId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Have great communication with the rest of the dev team, and also with the administrative team.",
                            ExperienceId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Realize code review of the tasks of the rest of the team.",
                            ExperienceId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Efficiently implement components, snippets, and sections of Shopify.",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Testing every new section created to ensure its working in different screen sizes.",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Priority user experience, make efficient js code.",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 14,
                            Description = "Defining project structure.",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 15,
                            Description = "Keep track of tasks and good communication with the designing and development team.",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ensure clean and understandable code (code review).",
                            ExperienceId = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Create and implement Vuejs components using domain-driven-design.",
                            ExperienceId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Estimate the time to implement requirements in hours in meetings with the team.",
                            ExperienceId = 4
                        },
                        new
                        {
                            Id = 19,
                            Description = "Follow the business requirements and use cases.",
                            ExperienceId = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "Good communication with the QA and development team.",
                            ExperienceId = 4
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ensure clean and understandable code and code refactorization.",
                            ExperienceId = 4
                        },
                        new
                        {
                            Id = 22,
                            Description = "Side help with Backend code analysis and DB.",
                            ExperienceId = 4
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Models.Technologie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("technologies", (string)null);
                });

            modelBuilder.Entity("PortfolioBackend.Models.TechnologieExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_id");

                    b.Property<int>("TechnologieId")
                        .HasColumnType("integer")
                        .HasColumnName("technologie_id");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("TechnologieId");

                    b.ToTable("technologies_experiences", (string)null);
                });

            modelBuilder.Entity("PortfolioBackend.Models.Responsabilitie", b =>
                {
                    b.HasOne("PortfolioBackend.Models.ProfessionalExperience", "ProfessionalExperience")
                        .WithMany("Responsabilities")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalExperience");
                });

            modelBuilder.Entity("PortfolioBackend.Models.TechnologieExperience", b =>
                {
                    b.HasOne("PortfolioBackend.Models.ProfessionalExperience", "ProfessionalExperience")
                        .WithMany("TechnologieExperiences")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioBackend.Models.Technologie", "Technologie")
                        .WithMany()
                        .HasForeignKey("TechnologieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfessionalExperience");

                    b.Navigation("Technologie");
                });

            modelBuilder.Entity("PortfolioBackend.Models.ProfessionalExperience", b =>
                {
                    b.Navigation("Responsabilities");

                    b.Navigation("TechnologieExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
