name: update project in server
description: create repository or update project in server
inputs:
  PORTFOLIO_IP:
    description: the ip address of the portfolio server
    required: true
runs:
  using: composite
  steps:
    - name: update project in server
      run: |
        ssh "root@${{ inputs.PORTFOLIO_IP }}" -i ~/.ssh/id_rsa "sudo ./app/scripts/new_update_project.sh"
      shell: bash