name: update project in server
description: create repository or update project in server
inputs:
  PORTFOLIO_IP:
    description: the ip address of the portfolio server
    required: true
  PORTFOLIO_SSH_KEY:
    description: the ssh key of the portfolio server
    required: true
runs:
  using: composite
  steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ inputs.PORTFOLIO_IP }}
        username: root
        key: ${{ inputs.PORTFOLIO_SSH_KEY }}
        script: |                          
          ~/app/scripts/pull_changes.sh
          ~/app/scripts/new_update_project.sh
    