name: update project in server
description: use invi-action to update project in server
runs:
  using: composite
  steps:
    - name: Update Server Through SSH
      uses: invi5H/ssh-action@v1
      with:
        SSH_HOST: ${{ secrets.PORTFOLIO_IP }}  
        SSH_USER: root
        SSH_KEY: ${{ secrets.PORTFOLIO_SSH_KEY }}
        SCRIPT: |
          sudo ./app/scripts/new_update_project.sh  
    