name: set id rsa
description: set id rsa for portfolio server connection

inputs:
  PORTFOLIO_SSH_KEY:
    description: the ssh key to use for portfolio server connection
    required: true
  PORTFOLIO_IP:
    description: the ip address of the portfolio server
    required: true

runs:
  using: composite
  steps:
   - name: set id rsa
     shell: bash
     run: |
        echo "creating ssh directory"
        mkdir -p ~/.ssh/
        echo "${{ inputs.PORTFOLIO_SSH_KEY }}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ inputs.PORTFOLIO_IP }}" >> ~/.ssh/known_hosts