name: installing postgres and use one query
on:
  push:
   branches:
     - master
jobs:
  installingPostgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: prueba

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Postgres CLI
        uses: akanieski/setup-postgres-cli@v0.1.2
        with:
          password: 1234
          commands: psql -h 127.0.0.1 -p 5432 -U postgres -d prueba -c "SELECT 1;"
      - name: Connect to db
        run: |
          psql -h 127.0.0.1 -p 5432 -U postgres -d prueba