name: installing postgres and use one query
on:
  push:
   branches:
     - master
jobs:
  installingPostgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: prueba
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Wait for PostgreSQL to be healthy
        run: |
          until [ "`docker inspect -f {{.State.Health.Status}} $(docker ps -q -f ancestor=postgres:15)`" == "healthy" ]; do
            echo "Waiting for PostgreSQL to be healthy..."
            sleep 5
          done
      - name: show docker processes
        run: docker ps
      - name: Setup Postgres CLI
        env:
          PGPASSWORD: 1234
          POSTGRES_PASSWORD: 1234
          PG_PASSWORD: 1234
        run: | 
          psql -h localhost -p 5432 -U postgres -d prueba -c "SELECT 1;"