name: connect to my portfolio server
on:
  push:
    branches:
      - master
jobs:
  testConnection:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.7
    - name: configura id_rsa
      run: |
        mkdir -p ~/.ssh/
        echo "${{ vars.PORTFOLIO_SSH_KEY }}" >> ~/.ssh/id_rsa
        ssh-keyscan -H "${{ vars.PORTFOLIO_IP }}" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
    - name: test connection
      run: |
        ssh "root@${{ vars.PORTFOLIO_IP }}" -i ~/.ssh/id_rsa "echo 'Connection successful from github actions' >> ~/github_actions/test.txt"