name: connect to my portfolio server
on:
  push:
    branches:
      - master
jobs:
  testConnection:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.7
    - name: configura id_rsa
      run: |
        echo "creating ssh directory"
        mkdir -p ~/.ssh/
        echo "${{ secrets.PORTFOLIO_SSH_KEY }}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.PORTFOLIO_IP }}" >> ~/.ssh/known_hosts
    - name: test connection
      run: |
        ssh "root@${{ secrets.PORTFOLIO_IP }}" -i ~/.ssh/id_rsa "echo 'Connection successful from github actions' >> ~/test.txt"