name: goona try env variables
on:
  push:
   branches:
     - master
jobs:
  testLocalVariable:
   runs-on: ubuntu-latest
   if: false
   env:
    JOB_SECRET: string:job_secret
   steps:
    - name: checkout
      uses: actions/checkout@v4.1.7
    - name: test variables
      env:
        STEP_SECRET: string:step_secret
      run: |
        echo $JOB_SECRET
        echo $STEP_SECRET
        echo ${{ vars.REPOSITORY_SECRET }}