name: "Mi firs workflow"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  installNode:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Install nvm and node latest version
      run: |
        chmod +x ./script.sh
        ./script.sh
        echo "Node version"
        node --version
            