name: "Mi firs workflow"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  installNode:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Install nvm
      run: |
        chmod +x ./nvm/install.sh
        ./nvm/install.sh
        echo "Instalación de nvm terminada"
    - name: Instalar ultima versión de node
      run: |
        chmod +x ./script.sh
        ./script.sh
    - name: Testear versión de node
      run: |
        chmod +x ./echo_node_version.sh
        ./echo_node_version.sh
            