name: 'Automatic Deploy'
on:
  push:
    branches:
      - master
jobs:
  testProject:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: update project in server
        uses: ./.github/actions/update_server
        with:
          PORTFOLIO_SSH_KEY: ${{ secrets.PORTFOLIO_SSH_KEY }}
          PORTFOLIO_IP: ${{ secrets.PORTFOLIO_IP }}