name: 'Automatic Deploy'
on:
  push:
    branches:
      - main
jobs:
  testProject:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: set env variables
        run: |
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env
          echo "DB_CONNECTION_STRING=${{ vars.DB_CONNECTION_STRING }}" >> .env
          echo "BACK_API_URI=${{ vars.BACK_API_URI }}" >> .env
      - name: check .env file
        run: cat .env
      - name: configure id rsa
        uses: ./.github/actions/configure_id_rsa
        with:
          PORTFOLIO_SSH_KEY: ${{ secrets.PORTFOLIO_SSH_KEY }}
          PORTFOLIO_IP: ${{ secrets.PORTFOLIO_IP }}
      - name: update project in server
        uses: ./.github/actions/update_server 
        with:
          PORTFOLIO_IP: ${{ secrets.PORTFOLIO_IP }}